name: 'capstone_bi'
version: '1.0.0'
config-version: 2
profile: 'capstone_bi'
model-paths: ["models"]
seed-paths:  ["seeds"]
test-paths:  ["tests"]
target-path: "target"
clean-targets: ["target"]
models:
  capstone_bi:
    staging:
      +schema:       silver
      +materialized: view
    marts:
      +schema:       gold
      +materialized: table
