name: 'customer_service_tickets'
version: '1.0.0'
config-version: 2

profile: 'customer_service'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]

models:
  retail_voice_analysis:
    staging:
      +materialized: view
    core:
      +materialized: table
