retail_voice:
  outputs:
    dev:
      type: postgres
      host: localhost
      user: root
      pass: root
      port: 5432
      dbname: customer_support_tickets_db
      schema: public
      threads: 4
  target: dev
